# Generated by Django 2.2 on 2019-04-22 23:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
