# Generated by Django 2.2 on 2019-04-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0002_auto_20190422_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(max_length=32),
        ),
    ]
