# Generated by Django 2.2 on 2019-04-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0003_auto_20190423_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawer',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawer_material', to='cabinets_app.Material'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
