# Generated by Django 2.2 on 2019-04-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0006_remove_hardware_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='catalog',
            field=models.CharField(choices=[('Laminate', 'Laminate'), ('Wood Slab', 'Wood Slab'), ('Wood 5-Piece', 'Wood 5-Piece'), ('Thermofoil', 'Thermofoil')], default='laminate', max_length=32),
        ),
        migrations.AlterField(
            model_name='specification',
            name='construction',
            field=models.CharField(choices=[('Frameless', 'Frameless'), ('Faceframe Overlay', 'Faceframe Overlay'), ('Faceframe Inset', 'Faceframe Inset')], default='frameless', max_length=32),
        ),
        migrations.AlterField(
            model_name='specification',
            name='finish_level',
            field=models.IntegerField(choices=[('Unfinished', 'Unfinished'), ('Sand & Prep Only', 'Sand & Prep Only'), ('Clear', 'Clear'), ('Stain', 'Stain'), ('Stain & Glaze', 'Stain & Glaze'), ('Stain & Distress', 'Stain & Distress'), ('Stain, Glaze & Distress', 'Stain, Glaze & Distress'), ('Paint', 'Paint'), ('Paint & Glaze', 'Paint & Glaze'), ('Paint & Distress', 'Paint & Distress'), ('Paint, Glaze & Distress', 'Paint, Glaze & Distress')], default=0),
        ),
    ]
