# Generated by Django 2.2 on 2019-04-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0008_auto_20190423_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='cabinets_app.Specification'),
        ),
    ]
