# Generated by Django 2.2 on 2019-04-24 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0010_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
