# Generated by Django 2.2 on 2019-04-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0011_auto_20190424_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='cabinets_app.Room'),
        ),
    ]
