# Generated by Django 2.2 on 2019-04-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0012_auto_20190424_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cabinets_app.Project'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='catalog',
            field=models.CharField(choices=[('Laminate', 'Laminate'), ('Wood Slab', 'Wood Slab'), ('Wood 5-Piece', 'Wood 5-Piece'), ('Thermofoil', 'Thermofoil')], default='Laminate', max_length=32),
        ),
        migrations.AlterField(
            model_name='specification',
            name='construction',
            field=models.CharField(choices=[('Frameless', 'Frameless'), ('Faceframe Overlay', 'Faceframe Overlay'), ('Faceframe Inset', 'Faceframe Inset')], default='Frameless', max_length=32),
        ),
    ]
