# Generated by Django 2.2 on 2019-04-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0015_auto_20190425_1316'),
        ('cabinets_app', '0015_auto_20190425_1152'),
    ]

    operations = [
    ]
