# Generated by Django 2.2.1 on 2019-06-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='notes',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
