# Generated by Django 2.2.1 on 2019-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0002_labor_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labor',
            options={'ordering': ('category', 'item_name')},
        ),
        migrations.AddField(
            model_name='hardware',
            name='category',
            field=models.CharField(choices=[('Hinges', 'Hinges'), ('Drawer Guides', 'Drawer Guides'), ('Knobs/Pulls', 'Knobs/Pulls'), ('Accessory', 'Accessory'), ('Misc.', 'Misc.')], default='Misc.', max_length=128),
        ),
    ]
