# Generated by Django 2.2.1 on 2019-05-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0003_auto_20190527_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ('category', 'name')},
        ),
    ]
