# Generated by Django 2.2.1 on 2019-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0005_auto_20190527_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(choices=[('Hinges', 'Hinges'), ('Drawer Guides', 'Drawer Guides'), ('Knobs/Pulls', 'Knobs/Pulls'), ('Accessories', 'Accessories'), ('Misc.', 'Misc.')], default='Misc.', max_length=128),
        ),
    ]
