# Generated by Django 2.2 on 2019-04-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0005_hardware_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='description',
        ),
    ]
