# Generated by Django 2.2.1 on 2019-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0006_auto_20190527_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('category', 'name')},
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Interior Material', 'Interior Material'), ('Exterior Material', 'Exterior Material')], default='Exterior Material', max_length=128),
        ),
        migrations.AddField(
            model_name='material',
            name='mat_type',
            field=models.CharField(choices=[('Sheet', 'Sheet'), ('Board', 'Board'), ('Moulding', 'Moulding')], default='Sheet', max_length=128),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
