# Generated by Django 2.2.1 on 2019-05-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0007_auto_20190527_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Interior Material', 'Interior Material'), ('Exterior Material', 'Exterior Material'), ('Drawer Material', 'Drawer Material')], default='Exterior Material', max_length=128),
        ),
    ]
