# Generated by Django 2.2 on 2019-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0007_auto_20190423_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='finish_level',
            field=models.CharField(choices=[('Unfinished', 'Unfinished'), ('Sand & Prep Only', 'Sand & Prep Only'), ('Clear', 'Clear'), ('Stain', 'Stain'), ('Stain & Glaze', 'Stain & Glaze'), ('Stain & Distress', 'Stain & Distress'), ('Stain, Glaze & Distress', 'Stain, Glaze & Distress'), ('Paint', 'Paint'), ('Paint & Glaze', 'Paint & Glaze'), ('Paint & Distress', 'Paint & Distress'), ('Paint, Glaze & Distress', 'Paint, Glaze & Distress')], default='Unfinished', max_length=125),
        ),
    ]
