# Generated by Django 2.2.1 on 2019-05-28 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0008_auto_20190527_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('billing_address', models.CharField(max_length=1024)),
                ('billing_phone', models.CharField(max_length=32)),
                ('billing_email', models.EmailField(max_length=256)),
                ('contact_name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cabinets_app.Company'),
        ),
    ]
