# Generated by Django 2.2 on 2019-04-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0013_auto_20190425_0933'),
        ('cabinets_app', '0013_auto_20190425_1000'),
    ]

    operations = [
    ]
