# Generated by Django 2.2 on 2019-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0014_merge_20190425_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labor',
            name='units',
        ),
        migrations.AddField(
            model_name='labor',
            name='unit_type',
            field=models.CharField(choices=[('Each', 'Each'), ('Pair', 'Pair'), ('Set', 'Set'), ('Sq Ft', 'Sq Ft')], default='Each', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardware',
            name='unit_type',
            field=models.CharField(choices=[('Each', 'Each'), ('Pair', 'Pair'), ('Set', 'Set')], max_length=16),
        ),
    ]
