# Generated by Django 2.2 on 2019-04-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0016_merge_20190425_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',)},
        ),
    ]
