# Generated by Django 2.2 on 2019-04-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0017_auto_20190425_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ('cabinet_number',)},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='labor',
            options={'ordering': ('item_name',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ('name',)},
        ),
    ]
