# Generated by Django 2.2 on 2019-04-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0016_merge_20190425_1441'),
        ('cabinets_app', '0016_merge_20190425_1442'),
        ('cabinets_app', '0018_auto_20190425_1518'),
    ]

    operations = [
    ]
