# Generated by Django 2.2 on 2019-04-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets_app', '0019_merge_20190425_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawer',
            options={'ordering': ('height',)},
        ),
    ]
